<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Orden">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="IdCliente" type="xs:string"/>
                <xs:element name="MetodoPago" type="xs:string"/>
                <xs:element name="Total" type="xs:decimal"/>
                <xs:element name="Estado">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Recibida"/>
                            <xs:enumeration value="Preparando"/>
                            <xs:enumeration value="ListaParaEntrega"/>
                            <xs:enumeration value="Completada"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>